### ISSUE TITLE
User Story: Load and select texts

### ISSUE THREAD

**Issue by gitayam** [irregularchat/Speech-Memorization-Platform#13]
As a user, I want to load and select texts so that I can practice memorizing them.

## Tasks:
- [ ] Add attributes to speech text files (Title, Text, Time limit, Description, Tags).
- [ ] Load pre-established text from files in the data/pre_texts/ directory.
- [ ] Create a sidebar for selecting texts.
