### ISSUE TITLE
User Story: Capture and process audio

### ISSUE THREAD

**Issue by gitayam** [irregularchat/Speech-Memorization-Platform#16]
As a user, I want the app to capture my speech and transcribe it to track my memorization progress.

## Tasks:
- [ ] Capture audio input from the microphone.
- [ ] Transcribe the audio input to text.
- [ ] Compare the transcribed text with the original text.
